# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

script: 
 - make build-mkdocs

deploy:
   provider: pages 
   skip-cleanup: true 
   github-token: $GITHUB_TOKEN
   local_dir: "./site"
   keep_history: true
   on:
    branch: main 

