# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

site_name: ChainBridge Docs
site_description: Modular Multi-Directional Blockchain Bridge to interact with Multiple Networks; Ethereum, Ethereum Classic, Substrate, Cosmos-SDK based chains.

repo_name: chainsafe/chainbridge
repo_url: https://github.com/ChainSafe/chainbridge

# Configuration
markdown_extensions:
  - meta
  - admonition
  - codehilite
  - toc:
      permalink: true

theme:
  name: material
  palette:
    primary: black
  favicon: img/favicon.ico
  custom_dir: overrides
nav:
  - Overview: index.md
  - Installation: installation.md
  - Configuration:
    - Overview: configuration.md
    - CLI Options: cli-options.md
  - Specification:
      - ChainBridge: spec.md
      - Ethereum:
        - Bridge Setup: chains/ethereum.md
        - Contracts: chains/eth-contracts.md
      - Substrate: chains/substrate.md
  - Guides:
    - Running Locally (EVM <-> Substrate): local.md
    - Deploying Live (EVM <-> EVM): live-evm-bridge.md
  - FAQ: faq.md
  - Testing: test.md
  - Releases:
      - Relayer: https://github.com/ChainSafe/ChainBridge/tags
      - Solidity: https://github.com/ChainSafe/chainbridge-solidity/tags


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ChainSafe/ChainBridge
