name: Deploy Docs

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build site
        uses: addnab/docker-run-action@v1
        with:
          image: squidfunk/mkdocs-material:latest
          options: -v ${{ env.working-directory }}:/docs -it build
      - name: Deploy GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
