name: cd

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mkdocs
        run: pip install mkdocs-material
      - name: Deploy site
        run: mkdocs gh-deploy --force
